// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backup combines an absolute backup directory with its validated manifest.
 */
export interface Backup {
    "path": string;
    "manifest": Manifest;
}

/**
 * BackupRequest contains all inputs needed to create a backup.
 */
export interface BackupRequest {
    "connection": Connection;
    "outputDirectory": string;
}

/**
 * Connection contains ephemeral SSH connection settings. Password fields must never be persisted.
 */
export interface Connection {
    "host": string;
    "identity"?: string;
    "password"?: string;
    "sudoPassword"?: string;
    "port"?: number;
    "useDefaultKeys"?: boolean;
}

/**
 * Device describes a whole physical restore destination.
 */
export interface Device {
    "id": string;
    "path": string;
    "name": string;
    "bytes": number;
    "transport": string;
    "removable": boolean;

    /**
     * Stable is true when ID comes from hardware/media identity rather than a reusable OS path.
     */
    "stable": boolean;
}

/**
 * Job is the serialisable state of a desktop background operation.
 */
export interface Job {
    "id": string;
    "type": string;
    "title": string;
    "subtitle": string;
    "status": string;
    "phase": string;
    "message": string;
    "bytes"?: number;
    "totalBytes"?: number;
    "fraction"?: number;
    "source"?: string;
    "destination"?: string;
    "startedAt": string;
    "completedAt"?: string | null;
    "error"?: string;
    "resultPath"?: string;
}

/**
 * Manifest is the durable metadata required to validate and restore a backup.
 */
export interface Manifest {
    "format": string;
    "formatVersion": number;
    "status": string;
    "consistency": string;
    "createdAt": string;
    "completedAt": string;
    "source": ManifestSource;
    "image": ManifestImage;
    "warning": string;
}

/**
 * ManifestImage records the compressed and uncompressed image integrity metadata.
 */
export interface ManifestImage {
    "file": string;
    "compression": string;
    "rawBytes": number;
    "compressedBytes": number;
    "sha256": string;
    "compressedSha256": string;
}

/**
 * ManifestSource records the system and whole-disk source used for a backup.
 */
export interface ManifestSource {
    "host": string;
    "hostname": string;
    "model": string;
    "os": string;
    "architecture": string;
    "device": string;
    "bytes": number;
    "logicalSectorSize"?: number;
    "rootFilesystem": string;
}

/**
 * PiInfo describes the source disk and access capabilities discovered over SSH.
 */
export interface PiInfo {
    "hostname": string;
    "model": string;
    "os": string;
    "architecture": string;
    "rootSource": string;
    "rootDisk": string;
    "rootFilesystem": string;
    "bootSource"?: string;
    "bootDisk"?: string;
    "diskSize": number;
    "logicalSectorSize"?: number;
    "sudoAvailable": boolean;
    "directDiskAccess": boolean;
    "passwordlessSudo": boolean;
    "sudoPasswordNeeded": boolean;
    "supported": boolean;
    "warnings": string[] | null;
}

/**
 * RestoreRequest contains the selected backup, target identifier, and erase confirmation.
 */
export interface RestoreRequest {
    "backupPath": string;
    "device": string;
    "confirmation": string;
    "verifyWrite": boolean;
}
