// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Backup {
    "path": string;
    "manifest": Manifest;
}

export interface BackupRequest {
    "connection": Connection;
    "outputDirectory": string;
}

export interface Connection {
    "host": string;
    "identity"?: string;
    "password"?: string;
    "port"?: number;
}

export interface Device {
    "id": string;
    "path": string;
    "name": string;
    "bytes": number;
    "transport": string;
    "removable": boolean;
}

export interface Job {
    "id": string;
    "type": string;
    "title": string;
    "subtitle": string;
    "status": string;
    "phase": string;
    "message": string;
    "bytes"?: number;
    "totalBytes"?: number;
    "fraction"?: number;
    "source"?: string;
    "destination"?: string;
    "startedAt": string;
    "completedAt"?: string | null;
    "error"?: string;
    "resultPath"?: string;
}

export interface Manifest {
    "format": string;
    "formatVersion": number;
    "status": string;
    "consistency": string;
    "createdAt": string;
    "completedAt": string;
    "source": ManifestSource;
    "image": ManifestImage;
    "warning": string;
}

export interface ManifestImage {
    "file": string;
    "compression": string;
    "rawBytes": number;
    "compressedBytes": number;
    "sha256": string;
    "compressedSha256": string;
}

export interface ManifestSource {
    "host": string;
    "hostname": string;
    "model": string;
    "os": string;
    "architecture": string;
    "device": string;
    "bytes": number;
    "logicalSectorSize"?: number;
    "rootFilesystem": string;
}

export interface PiInfo {
    "hostname": string;
    "model": string;
    "os": string;
    "architecture": string;
    "rootSource": string;
    "rootDisk": string;
    "rootFilesystem": string;
    "bootSource"?: string;
    "bootDisk"?: string;
    "diskSize": number;
    "logicalSectorSize"?: number;
    "sudoAvailable": boolean;
    "supported": boolean;
    "warnings": string[] | null;
}

export interface Progress {
    "phase": string;
    "message": string;
    "bytes"?: number;
    "totalBytes"?: number;
    "fraction"?: number;
    "source"?: string;
    "destination"?: string;
}

export interface RestoreRequest {
    "backupPath": string;
    "device": string;
    "confirmation": string;
    "verifyWrite": boolean;
}

export interface RestoreResult {
    "device": string;
    "bytesWritten": number;
    "verified": boolean;
    "ejected": boolean;
    "manifest": Manifest;
}

export interface VerifyResult {
    "valid": boolean;
    "rawBytes": number;
    "sha256": string;
    "compressedSha256": string;
    "manifest": Manifest;
}
