// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DeviceConfig {
    "version": number;
    "devices": SavedDevice[] | null;
    "selectedDeviceId"?: string;
}

/**
 * SaveDeviceRequest deliberately separates ephemeral secrets from durable data.
 */
export interface SaveDeviceRequest {
    "device": SavedDevice;
    "password"?: string;
    "copyPasswordFromId"?: string;
}

/**
 * SavedDevice contains persistent settings, never passwords or key contents.
 */
export interface SavedDevice {
    "id": string;
    "name": string;
    "username": string;
    "host": string;
    "port": number;
    "authMethod": string;
    "identity"?: string;
    "outputDirectory": string;
    "rememberPassword": boolean;
    "credentialRef"?: string;
}
