// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export function Backup(request: core$0.BackupRequest): $CancellablePromise<core$0.Backup> {
    return $Call.ByID(2781755494, request);
}

export function CancelJob(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(574686037, id);
}

export function DefaultBackupDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2391739798);
}

export function Inspect(connection: core$0.Connection): $CancellablePromise<core$0.PiInfo> {
    return $Call.ByID(3471385580, connection);
}

export function ListBackups(directory: string): $CancellablePromise<core$0.Backup[] | null> {
    return $Call.ByID(1648335255, directory);
}

export function ListDevices(): $CancellablePromise<core$0.Device[] | null> {
    return $Call.ByID(1949135979);
}

export function ListJobs(): $CancellablePromise<core$0.Job[] | null> {
    return $Call.ByID(1494729520);
}

export function PauseJob(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(552944717, id);
}

export function Restore(request: core$0.RestoreRequest): $CancellablePromise<core$0.RestoreResult> {
    return $Call.ByID(2046745482, request);
}

export function ResumeJob(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3427591970, id);
}

export function SelectBackup(): $CancellablePromise<core$0.Backup> {
    return $Call.ByID(3412266126);
}

export function SelectBackupDirectory(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2841325653, currentPath);
}

export function SelectIdentityFile(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(4266495620, currentPath);
}

export function StartBackup(request: core$0.BackupRequest): $CancellablePromise<core$0.Job> {
    return $Call.ByID(1788376522, request);
}

export function StartRestore(request: core$0.RestoreRequest): $CancellablePromise<core$0.Job> {
    return $Call.ByID(1353658238, request);
}

export function Verify(backupPath: string): $CancellablePromise<core$0.VerifyResult> {
    return $Call.ByID(1909698437, backupPath);
}
